## PROPS ##
SERVER_PORT: TBD
LOGGING_LEVEL: INFO
DATABASE_IP: TBD
DATABASE_PORT: TBD
DATABASE_USERNAME: TBD
DATABASE_PASSWORD: TBD
KAFKA_BOOSTRAP_SERVERS: TBD
KAFKA_CONSUMER_GROUP_ID: TBD
JWT_SECRET: TBD
JWT_EXPIRATION_MS: TBD