## PROPS ##
SERVER_PORT: 8081
LOGGING_LEVEL: DEBUG

DATABASE_IP: localhost
DATABASE_PORT: 5433
DATABASE_NAME: dbAuth
DATABASE_USERNAME: dbAuth
DATABASE_PASSWORD: dbAuth

JWT_SECRET: MySup3rJwtS3cr3tD3v!
JWT_EXPIRATION_MS: 86400000

SERVICE_REGISTRY_URL: localhost
SERVICE_REGISTRY_PORT: 8761
SERVICE_REGISTRY_USERNAME: eureka-user
SERVICE_REGISTRY_PASSWORD: eureka-pw

COMMON_PRINTSTACKTRACE: true