## PROPS ##
SERVER_PORT: 8081
LOGGING_LEVEL: DEBUG
DATABASE_IP: localhost
DATABASE_PORT: 5433
DATABASE_NAME: dbAuth
DATABASE_USERNAME: dbAuth
DATABASE_PASSWORD: dbAuth
#KAFKA_BOOSTRAP_SERVERS: localhost:29092,localhost:39092
#KAFKA_CONSUMER_GROUP_ID: authConsumerGroup
JWT_SECRET: MySup3rJwtS3cr3tD3v!
JWT_EXPIRATION_MS: 86400000